### ISSUE TITLE
4.3% of sky fibers have ZWARN==0 

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#102]
Using the full performance of redrock on eBOSS, we have:
`3,059,850` fibers,  `282,341` (`9.2`%) are sky fibers, `24,100` have ZWARN==0 (`8.5`%, `0.8`% of total)
Redrock classifies these sky fibers as mostly galaxies. This is logical since the galaxy template has 10 PCAs, when stars have 5 and QSOs has 4.
```
CLASS  || all   || ZWARN==0 ||
STAR   || 0.4%  || 1.7%     ||
GALAXY || 97.8% || 95.1%    ||
QSO    || 1.8%  || 3.2%     ||
```

Here are the fake redshift distribution for these three classes.
It is possible that some sky-fibers have objects in them but it wouldn't produce sharp distributions.

![as_star_oldmaster](https://user-images.githubusercontent.com/3166436/36573427-204b3bd6-17fe-11e8-8013-d85ee460b722.png)
![as_galaxy_oldmaster](https://user-images.githubusercontent.com/3166436/36573428-2062053c-17fe-11e8-982d-3d185cc8e338.png)
![as_qso_oldmaster](https://user-images.githubusercontent.com/3166436/36573426-20371d0e-17fe-11e8-8ebd-50f6e903d609.png)

The list of eBOSS sky fibers is in:
`/global/homes/h/hdumasde/Run_programs/desi/redrock/look_sky_fibers/list_sky_fibers.txt`

**Comment by moustakas** [comment]
In [PRIMUS](https://primus.ucsd.edu) we included a power-law "template".  I.e., if a spectrum was indistinguishable from a power-law then we flagged this with a dedicated zwarning flag.  I wonder if many of these false-positives would be flagged by something along these lines.

**Comment by londumas** [comment]
@moustakas, The issue with this method is that the mis-calibration of the sky results in apparent emission lines or anti-emission lines. This method you suggest only uses broadbands. It removes some sky fibers but not all because the galaxy template has very sharp emission lines that can fit better the sky mis-calibrated lines. I had a look.

**Comment by londumas** [comment]
We could also play on the minimum Delta chi2 between two best fit.
Currently it is set to 9.

**Comment by londumas** [comment]
Here is a small study of the completeness vs. purity for the three classes with full eBOSS.
In each plot the blue curve gives the cumulative number of objects with ZWARN==0 or ZWARN==SMALL_DELTA_CHI2.
The orange line gives the percent of these objects not being a sky fiber.
The black line is the 99% purity.

If we target 99% purity, then:
- STAR: DeltaChi2 min ~ 4, only 90% objects survive
- GALAXY: Delta chi2 min ~ 50, only 78% objects survive
- QSO:  Delta chi2 min ~30 , only 94% objects survive

If we target 95% purity, then:
- STAR: DeltaChi2 min = 0, all objects survives
- GALAXY: Delta chi2 min ~ 30, only 80% objects survive
- QSO:  Delta chi2 min ~ 14, only 96% objects survive

![purity_stars](https://user-images.githubusercontent.com/3166436/37169067-12497e00-22c4-11e8-9b9e-dc082ff7d79f.png)

![purity_galaxies](https://user-images.githubusercontent.com/3166436/37169069-127a947c-22c4-11e8-9eed-05bedf4a4fcd.png)

![purity_qsos](https://user-images.githubusercontent.com/3166436/37169068-12632788-22c4-11e8-9d30-2b09302a4e7f.png)

**Comment by londumas** [comment]
Thanks to archetypes, this number dropped by more than half: from `10%` to `4.3%`.
The current confusion matrix for `ZWARN==0` sky fiber is:
```
                         | GALAXY  | QSO     | STAR    | 
SKY                14888 |  71.43  |  17.09  |  11.49  | 
```

Here are the distribution of sky fibers:

![star_contamination](https://user-images.githubusercontent.com/3166436/42099135-ec1bb0d6-7b79-11e8-8108-6077444aa18c.png)

![galaxy_contamination](https://user-images.githubusercontent.com/3166436/42099137-ec50ece2-7b79-11e8-8a2f-a3fba4be4d22.png)

![quasar_contamination](https://user-images.githubusercontent.com/3166436/42099136-ec359942-7b79-11e8-9f17-9ed262b5e511.png)

**Comment by moustakas** [comment]
This is a very nice study but not really an open ticket anymore. I've added a note to the DR1 paper where we could consider including this type of analysis.
