### ISSUE TITLE
ZWARN=1024 in high-z QSOs

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#115]
In runs with latest master of desisim / desispec / specter, ~half of the low redshift QSOs have ZWARN=1024 (BAD_MINFIT).  See cell 75 of
https://github.com/desihub/desitest/blob/master/mini/minitest.ipynb

I'm pretty certain that this was not the case for the 18.3 reference run, but I'll have to dig out the minitest commit that contains that (and then tag for 18.3...).  So I think it is a recent problem, but either way it is something that needs to be fixed.

**Comment by londumas** [comment]
Could you give an example of such a QSO?
Is that the reason why there is a gap in the QSO plot of cell 73, or it is another issue?

**Comment by sbailey** [comment]
Correction: it is the high redshift QSOs that have a problem, not the low redshift ones (in the QA table, QSO_L means Lyman-alpha QSO, not Low-z QSO...).

The redshift gap is due to a mis-match in coverage in the mocks and is unrelated.

Files are /global/cscratch1/sd/sjbailey/desi/dev/end2end/spectro/redux/mini.  Example (healpix,targetid):

```python
from astropy.table import Table
import healpy
zcat = Table.read('zcatalog-mini.fits')
isqso = zcat['SPECTYPE'] == 'QSO   '  #- with spaces, sigh
ishiz = zcat['Z'] > 2.1
is1024 = zcat['ZWARN'] == 1024
print(np.count_nonzero(isqso & ishiz & is1024), np.count_nonzero(isqso & ishiz))

isbad = (isqso & ishiz & is1024)
ra = zcat['RA'][isbad]
dec = zcat['DEC'][isbad]
targetid = zcat['TARGETID'][isbad]
healpix = healpy.ang2pix(64, ra, dec, nest=True, lonlat=True)
list(zip(healpix, targetid))
```

```
[(5263, 288230398226337452),
 (5263, 288230398226337460),
 (5263, 288230398226337464),
 (5274, 288230398272474535),
 (5274, 288230398272474537),
 (5274, 288230398272474538),
 (5274, 288230398272474539),
 (5274, 288230398272474540),
...
 (5652, 288230399857921151),
 (5652, 288230399857921155),
 (5652, 288230399857921157),
 (5652, 288230399857921158),
 (5652, 288230399857921162),
 (5652, 288230399857921164),
 (5653, 288230399862115367),
 (5653, 288230399862115375),
 (5653, 288230399862115382),
 (5654, 288230399866309939)]
```

**Comment by londumas** [comment]
Sending the production of one of the healpix with the current master, I have no BAD_MINFIT.
What version of redrock was used? With which options? 
```
rrdesi /global/cscratch1/sd/sjbailey/desi/dev/end2end/spectro/redux/mini/spectra-64/52/5263/spectra-64-5263.fits --output redrock-64-5263.h5 --zbest zbest-64-5263.h5
```

**Comment by sbailey** [comment]
I confirm that I don't get the ZWARN=1024 when using rrdesi, but I do get them when using rrdesi_mpi, e.g.
```
srun -A desi -t 30:00 -C haswell --qos interactive -N 1 -n 32 -c 2  \
    rrdesi_mpi spectra-64/52/5263/spectra-64-5263.fits \
    --output spectra-64/52/5263/redrockmpi-64-5263.h5 \
    --zbest spectra-64/52/5263/zbestmpi-64-5263.fits
```
Comparing the chi2 vs. z for the MPI vs. multiprocessing versions, the difference appears for z>1.938 .  Is it possible that @londumas correction for mean Lyman-alpha absorption vs. z is being applied only for multiprocessing and not for MPI parallelism?

![zchi2](https://user-images.githubusercontent.com/218471/39613009-180d9048-4f19-11e8-9481-95a052965a6f.png)

![zchi2_diff](https://user-images.githubusercontent.com/218471/39612961-cefae18a-4f18-11e8-8338-e30ed6379fbe.png)

**Comment by londumas** [comment]
@sbailey, I found. It is indeed because the way to deal with templates when doing mpi is different than when doing multiprocessing. It boils to the condition `if self._comm is not None:` in the `init` method of `DistTemplate`. Let me fix this.

**Comment by londumas** [comment]
Fixed in https://github.com/desihub/redrock/pull/117
