### ISSUE TITLE
QSO:::BAL have a high failure rate

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#129]
Most of the failures of quasars in redrock+archetype are linked to BALs.
Regular QSO have a near `97%` good rate and `1.5%` failure rate, whereas BAL QSO have a `82%` good rate and `13.3%` failure rate.
The current PCAs and archetypes don't have BAL in them.
Currently desisim.SIMQSO can't be used to produce neither PCA nor archetypes and don't have BALs.

Using DR12_superSet:

All
```
                   ntarg   good  fail  miss  lost
GALAXY             22788  87.85 10.27  0.44  1.44
QSO               295310  95.43  2.63  0.59  1.34
STAR              205250  88.96  2.10  5.51  3.44

                         | GALAXY  | QSO     | STAR    | 
GALAXY             22360 |  95.21 |   3.70 |   1.08 | 
QSO               289597 |   1.31 |  98.57 |   0.11 | 
STAR              186894 |   1.79 |   0.57 |  97.65 |
```

No BAL
```
                   ntarg   good  fail  miss  lost
GALAXY             22788  87.85 10.27  0.44  1.44
QSO               266058  96.89  1.47  0.58  1.06
STAR              205250  88.96  2.10  5.51  3.44

                         | GALAXY  | QSO     | STAR    | 
GALAXY             22360 |  95.21 |   3.70 |   1.08 | 
QSO               261701 |   1.10 |  98.81 |   0.09 | 
STAR              186894 |   1.79 |   0.57 |  97.65 | 
```

Only BAL
```
                   ntarg   good  fail  miss  lost
QSO                29252  82.13 13.23  0.68  3.95

                         | GALAXY  | QSO     | STAR    | 
QSO                27896 |   3.29 |  96.38 |   0.33 |
```

**Comment by andreufont** [comment]
Hi Helion,

These type of tests are very important. Jaime, Luz Angela and Alma (added
in this email) have looked at adding BALs in SIMQSO, but I'm not sure about
the status of this effort. Any update?

Best,
Andreu

**Comment by forero** [comment]
@andreufont Luz is quickly ramping up on python+desihub. We hope to have a PR to discuss by the lya telecon next week.

**Comment by moustakas** [comment]
This is a known issue but we did reasonably well for the Y1 analyses, but we can always do better. Closing this ticket but let's revisit this question once the new set of Y3 (see #280) templates are in place.
