### ISSUE TITLE
minimum redshift for galaxies:BGS

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#135]
What is the expected minimum redshift for BGS in desi?
Currently we go down to `z=0.005` for galaxies, this is an issue for low redshift galaxies, that are thus
given a higher redshift by redrock. Example: `plate=266`, `mjd=51602`,` fiber=0089`: `z_redrock = 0.316`, `z_spall = 0.0048`:
http://skyserver.sdss.org/dr12/en/tools/explore/summary.aspx?plate=266&mjd=51602&fiber=89

The following plot gives z_redrock vs. z_spall for DR7 galaxies with low redshift.

![spall_vs_redrock_dr7](https://user-images.githubusercontent.com/3166436/43928091-e9548a56-9bec-11e8-9552-a5f7a6307439.png)

**Comment by moustakas** [comment]
In AGES (flux-limited to I<20.5 over 9 deg^2) galaxy redshifts extended as low as `z=0.001` but in principle they could have gone (slightly) negative.  We should definitely extend the minimum redshift range to capture nearby, blueshifted galaxies.

**Comment by londumas** [comment]
@moustakas, Thank you for the answer. How much negative could they go?

**Comment by moustakas** [comment]
Here's a better dataset for answering this question -- the [NASA-Sloan Atlas](http://www.nsatlas.org). Looks like the redshift distribution extends to `z~-0.0033`, although DESI will cover more volume...

<img width="600" alt="screen shot 2018-08-10 at 7 03 27 am" src="https://user-images.githubusercontent.com/1431820/43954795-cab18c1e-9c6b-11e8-8442-a507bd25fb8c.png">

**Comment by londumas** [comment]
I just tried sending the ELG+LRG SDSS truth table and some DR7 plates.
It works very well at recovering the proper redshift for these objects with `z<0.005`.
However, we get a confusion between BGS and STAR. Multiple objects have the same redshift `z~0`,
but used to be called STAR and are now called GALAXY.
Can someone have a look and tell me what these objects truly are: STAR, GALAXY, or little of both.
Do we care to have the proper SPECTYPE for these objects or the redshift is enough?

Here is the list of objects for https://dr14.sdss.org/optical/spectrum/view
7292, 56709, 80
7292, 56709, 107
7292, 56709, 157
7292, 56709, 296
7292, 56709, 452
7292, 56709, 462
7292, 56709, 481
7292, 56709, 754
7292, 56709, 806
7292, 56709, 821
7292, 56709, 822
7306, 56663, 128
7306, 56663, 144
7306, 56663, 206
7306, 56663, 210
7306, 56663, 281
7306, 56663, 291
7306, 56663, 298
7306, 56663, 360
7306, 56663, 392
7306, 56663, 464
7306, 56663, 504
7306, 56663, 598
7306, 56663, 606
7306, 56663, 616
7306, 56663, 746
7306, 56663, 800
7306, 56663, 834
7306, 56663, 918
7306, 56663, 951
7306, 56663, 1000
7306, 56684, 90
7306, 56684, 104
7306, 56684, 168
7306, 56684, 204
7306, 56684, 228
7306, 56684, 286
7306, 56684, 287
7306, 56684, 314
7306, 56684, 321
7306, 56684, 322
7306, 56684, 478
7306, 56684, 502
7306, 56684, 586
7306, 56684, 594
7306, 56684, 610
7306, 56684, 654
7306, 56684, 702
7306, 56684, 732
7306, 56684, 788
7306, 56684, 830
7306, 56684, 941
7306, 56684, 998
7309, 56991, 14
7309, 56991, 66
7309, 56991, 74
7309, 56991, 94
7309, 56991, 99
7309, 56991, 152
7309, 56991, 193
7309, 56991, 217
7309, 56991, 220
7309, 56991, 305
7309, 56991, 434
7309, 56991, 442
7309, 56991, 457
7309, 56991, 658
7309, 56991, 688
7309, 56991, 724
7309, 56991, 738
7309, 56991, 771
7309, 56991, 774
7309, 56991, 788
7309, 56991, 794
7309, 56991, 978
7309, 56991, 980
7317, 56992, 92
7317, 56992, 101
7317, 56992, 104
7317, 56992, 119
7317, 56992, 134
7317, 56992, 193
7317, 56992, 211
7317, 56992, 228
7317, 56992, 239
7317, 56992, 240
7317, 56992, 319
7317, 56992, 396
7317, 56992, 397
7317, 56992, 404
7317, 56992, 417
7317, 56992, 443
7317, 56992, 499
7317, 56992, 516
7317, 56992, 532
7317, 56992, 554
7317, 56992, 560
7317, 56992, 575
7317, 56992, 610
7317, 56992, 642
7317, 56992, 662
7317, 56992, 663
7317, 56992, 727
7317, 56992, 778
7317, 56992, 790
7317, 56992, 814
7317, 56992, 820
7317, 56992, 880
7317, 56992, 896
7382, 56772, 8
7382, 56772, 28
7382, 56772, 49
7382, 56772, 290
7382, 56772, 314
7382, 56772, 330
7382, 56772, 404
7382, 56772, 563
7382, 56772, 564
7382, 56772, 625
7382, 56772, 646
7382, 56772, 678
7382, 56772, 684
7382, 56772, 776
7382, 56772, 800
7382, 56772, 824
7382, 56772, 839
7382, 56772, 947
7382, 56991, 9
7382, 56991, 24
7382, 56991, 74
7382, 56991, 292
7382, 56991, 456
7382, 56991, 506
7382, 56991, 564
7382, 56991, 566
7382, 56991, 569
7382, 56991, 678
7382, 56991, 682
7382, 56991, 778
7382, 56991, 796
7382, 56991, 824
7382, 56991, 837
7382, 56991, 949
7396, 56809, 12
7396, 56809, 22
7396, 56809, 80
7396, 56809, 147
7396, 56809, 206
7396, 56809, 228
7396, 56809, 264
7396, 56809, 307
7396, 56809, 550
7396, 56809, 599
7396, 56809, 818
7396, 56809, 910
7396, 56809, 956
7407, 56772, 109
7407, 56772, 173
7407, 56772, 222
7407, 56772, 256
7407, 56772, 262
7407, 56772, 349
7407, 56772, 425
7407, 56772, 439
7407, 56772, 473
7407, 56772, 568
7407, 56772, 575
7407, 56772, 576
7407, 56772, 598
7407, 56772, 637
7407, 56772, 640
7407, 56772, 648
7407, 56772, 707
7407, 56772, 716
7407, 56772, 802
7407, 56772, 806
7407, 56772, 808
7407, 56772, 810
7407, 56772, 829
7407, 56772, 859
7407, 56772, 865
7407, 56772, 972
7407, 56772, 976
7428, 56781, 9
7428, 56781, 35
7428, 56781, 94
7428, 56781, 129
7428, 56781, 168
7428, 56781, 194
7428, 56781, 200
7428, 56781, 212
7428, 56781, 244
7428, 56781, 353
7428, 56781, 365
7428, 56781, 401
7428, 56781, 470
7428, 56781, 524
7428, 56781, 555
7428, 56781, 591
7428, 56781, 596
7428, 56781, 629
7428, 56781, 682
7428, 56781, 698
7428, 56781, 746
7428, 56781, 748
7428, 56781, 749
7428, 56781, 800
7428, 56781, 849
7428, 56781, 854
7428, 56781, 909
7428, 56781, 916
7428, 56781, 968
7428, 56781, 994
7596, 56945, 18
7596, 56945, 143
7596, 56945, 316
7596, 56945, 372
7596, 56945, 516
7596, 56945, 754
7596, 56945, 783
7596, 56945, 889
7596, 56945, 917
7596, 56945, 919
7596, 56945, 970
7610, 56980, 116
7610, 56980, 152
7610, 56980, 428
7610, 56980, 831
7610, 56980, 851
7610, 56980, 870
7610, 56980, 992
7659, 57060, 92
7659, 57060, 93
7659, 57060, 96
7659, 57060, 336
7659, 57060, 362
7659, 57060, 412
7659, 57060, 518
7659, 57060, 564
7659, 57060, 689
7659, 57060, 710
7659, 57060, 754
7659, 57060, 770
7681, 57042, 5
7681, 57042, 302
7681, 57042, 318
7681, 57042, 490
7681, 57042, 544
7681, 57042, 776
7681, 57042, 989
7834, 56979, 365
7834, 56979, 440
7834, 56979, 602
7834, 56979, 764
7839, 56900, 23
7839, 56900, 120
7839, 56900, 278
7839, 56900, 336
7839, 56900, 627
7843, 56902, 372
7843, 56902, 590
7843, 56902, 681
7843, 56902, 786
7848, 56959, 89
7848, 56959, 272
7848, 56959, 417
7848, 56959, 890
7848, 56959, 903
9236, 57685, 515
9236, 57685, 698
9236, 57685, 965

**Comment by moustakas** [comment]
The spectral classification is important, although I guess it's secondary to the redshift. In BGS we will make a valiant effort to exclude stars in target selection (just as SDSS/Main and GAMA did using their star-galaxy separation criteria), so hopefully the contamination level from stars will be relatively low. 

I spot-checked about 15 of the spectra you listed and most of them look like stars to me.  I think this is where the photometry is going to be very helpful -- the optical-WISE colors of the stars and galaxies are going to be very different (although we're going to use those colors for star-galaxy separation...).

**Comment by londumas** [comment]
@moustakas, Thank you for the answers.
Would you say we should merge a branch looking for `z<0.005` for galaxies even though there is a confusion between type BGS and type STAR? or we should wait to solve this confusion? What would the BGS team prefer? I bet they prefer a proper redshift, even if the type is not correct.
