### ISSUE TITLE
Error when coadding multiple observations

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#148]
When using all observations available, thanks to the `run_on_one_thingid_across_different_plate` branch (https://github.com/desihub/redrock/pull/147), I get an error when there is a large amount of observations, here 84. For smaller numbers of observations, I have no errors.
This error is at the level of the coadds.

I am investigating.

```
Proc 0: Traceback (most recent call last):
Proc 0:   File "/uufs/astro.utah.edu/common/home/u6011908/Programs/desi/code/redrock/py/redrock/external/boss.py", line 431, in rrboss
    cache_Rcsr=True)
Proc 0:   File "/uufs/astro.utah.edu/common/home/u6011908/Programs/desi/code/redrock/py/redrock/external/boss.py", line 262, in read_spectra
    targets.append(Target(targetid, spectra, coadd=coadd, meta=tmeta))
Proc 0:   File "/uufs/astro.utah.edu/common/home/u6011908/Programs/desi/code/redrock/py/redrock/targets.py", line 126, in __init__
    self.compute_coadd()
Proc 0:   File "/uufs/astro.utah.edu/common/home/u6011908/Programs/desi/code/redrock/py/redrock/targets.py", line 162, in compute_coadd
    Rdiags += s.R.data * s.ivar
Proc 0: ValueError: operands could not be broadcast together with shapes (9,4477) (13,4477) (9,4477) 

Total run time: 35.9 seconds
```

The huge command to run is:
```
rrboss
--archetypes $HOME/Programs/desi/code/redrock/py/redrock/archetypes/
--zbest zbest-0-4.fits
--output rrdetail-0-4.h5
--spplate  $BOSS_SPECTRO_REDUX/v5_10_10/7339/spPlate-7339-57481.fits $BOSS_SPECTRO_REDUX/v5_10_10/7339/spPlate-7339-57510.fits
--targetids 497438223
```

**Comment by sbailey** [comment]
Check the dimensionality of the resolution data that it is creating from the input spPlate files.  It looks like in once case it is generating 9 diagonal elements and in another it is generating 13 diagonal elements, and then failing to add them without special indexing logic.

**Comment by londumas** [comment]
The issue comes from the fact that the size of the two sparse diagonal (`sparse.dia_matrix`) resolution matrix are not the same. This happens because the maximum of the ' Wavelength dispersion in pixels' is different enough. An easy fix is not to coadd these two observations, by transforming `self.wavehash` from:
```
self.wavehash = hash((len(wave), wave[0], wave[1], wave[-2], wave[-1]))
```
to:

```
self.wavehash = hash((len(wave), wave[0], wave[1], wave[-2], wave[-1], R.data.shape[0]))
```
Would that be ok for you @sbailey?

**Comment by londumas** [comment]
fixed in https://github.com/desihub/redrock/pull/147
