### ISSUE TITLE
rrgaltemplate is broken

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#150]
The PCA production is broken in the current Master, it seems to be linked to `desisim/py/desisim/templates.py`. @moustakas, do you have an idea what could be happening?

```
python rrgaltemplate --outfile test_new_gal_PCA.fits --version 0.0
INFO:io.py:937:read_basis_templates: Reading $HOME/Programs/desi//spectro/templates/basis_templates/v2.5/elg_templates_v2.0.fits
Traceback (most recent call last):
  File "own_rrgaltemplate.py", line 51, in <module>
    tflux, twave, tmeta = ELG().make_templates(nelg, restframe=True, nocolorcuts=True,seed=opts.seed)
  File "$HOME/Programs/desi/code/desisim/py/desisim/templates.py", line 913, in __init__
    add_SNeIa=add_SNeIa)
  File "$HOME/Programs/desi/code/desisim/py/desisim/templates.py", line 397, in __init__
    self.normfilt_north = filters.load_filters(self.normfilter_north)
  File "/global/common/software/desi/edison/desiconda/20170920-1.2.0-spec/conda/lib/python3.6/site-packages/speclite/filters.py", line 1711, in load_filters
    responses.append(load_filter(name))
  File "/global/common/software/desi/edison/desiconda/20170920-1.2.0-spec/conda/lib/python3.6/site-packages/speclite/filters.py", line 1785, in load_filter
    .format(valid.group(1), filter_group_names))
ValueError: No such group 'BASS'. Choose one of ['sdss2010', 'decam2014', 'wise2010', 'lsst2016', 'bessell'].
```

**Comment by moustakas** [comment]
The new filter set is only in `speclite/master`.  A tag by @dkirkby is coming soon, I think, or you can check out the master branch.

I likely broke many other things, so please keep posting them and I'll fix them ASAP.

**Comment by londumas** [comment]
@moustakas, I can wait for the branch to be merged, could you tell here when it should be fixed, so I can test?
I always use the master of all desi packages, so the bug is in it.

**Comment by moustakas** [comment]
With desisim and speclite master checked out, this works just fine (although note that the various templates classes now return *four* values, not three) (see the documentation):
```
from desisim.templates import ELG
tflux, twave, tmeta, tobjmeta = ELG().make_templates(3, restframe=True, nocolorcuts=True, seed=1)
```
The Traceback clearly shows that you're using an older version of `speclite`, which doesn't know about the MzLS+BASS filters.
```
import speclite
print(speclite.__version__)
0.8dev495
```

**Comment by londumas** [comment]
Indeed, I was using an old version of desiconda. However, it is still not working in the latest `20180709-1.2.6-spec` version. Let me test by getting it directly form https://github.com/dkirkby/speclite

**Comment by londumas** [comment]
@moustakas, Thank you, it works.

**Comment by londumas** [comment]
fixed in PR https://github.com/desihub/redrock/pull/153
