### ISSUE TITLE
numba is commented

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#163]
I realized that numba is commented, is that normal?

https://github.com/desihub/redrock/blob/1ef2d19a0cad69fd9f9b906c59ac7af9177b3fdd/py/redrock/_zscan.py#L16

**Comment by sbailey** [comment]
Thanks for noticing this.  That appears leftover from some optimization testing.  This code makes good use by numpy functions and isn't optimized for numba.  I opened PR #164 to clean this up.

**Comment by londumas** [comment]
fixed in https://github.com/desihub/redrock/pull/164
