### ISSUE TITLE
rrdesi comm.Abort() interferes with desispec pipeline TimeoutError

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#169]
`redrock.external.desi.rrdesi` has a fairly blunt "fail early fail often" mechanism:
```python
...
try:
    [stuff]
except:
    [print traceback]
    if comm is not None:
        comm.Abort()
```

The original motivation for this was that when running rrdesi by itself, exceptions on one rank were causing that rank to hang while other ranks stayed alive waiting for it to catch up at `comm.barrier`, `comm.bcast`, etc. steps and rrdesi would never exit until killed (with the error possibly stuck in stdout/stderr buffering).  Printing a traceback and calling `comm.Abort()` at least got us an error message and exited as soon as the problem occurred.

However, `desispec.pipeline.run.run_task` wraps each task with a timeout signal handler so that if a task gets bogged down on something like an slow I/O issue, it doesn't waste the full jobtime before getting killed.  The problem?  rrdesi is catching that `TimeoutException` and calling `comm.Abort()` without passing it back up the chain for the pipeline to gracefully mark that task as failed and move on with the others.  This is also killing off all other tasks running at the same time.

A few options:
* special case `TimeoutError` and re-raise that and only that.
  * This would fix this particular case, but still leaves us vulnerable to other
    single-rank exceptions taking down an entire production instead of
    cleanly failing on just that single task.
* add a `no_mpi_abort` option to rrdesi that the pipeline could use to
  prevent it from calling `comm.Abort()`, and having it re-raise whatever
  exceptions it finds instead.
  * This would also work for the `TimeoutError` because it is raised on all ranks, but it leaves us susceptible to the original problem of a single-rank exception blocking the code while the other ranks wait forever at some MPI barrier.  When run by `desispec.pipeline.run.run_task` the other ranks would eventually be interrupted by a `TimeoutError` so maybe that's ok.
* other?

I think what we really want doesn't exist within MPI: a way for one rank to force an exception on another rank without the full brutality of an MPI abort taking down the entire global communicator.

**Comment by tskisner** [comment]
The pipeline simply requires that if running an MPI-enabled task, then if one rank raises an exception all processes should raise an exception.  For example, in the specex MPI wrapper:

**Comment by tskisner** [comment]
(Previous comment posted early)

The pipeline simply requires that if running an MPI-enabled task, then if one rank raises an exception all processes should raise an exception. For example, in the specex MPI wrapper:

https://github.com/desihub/desispec/blob/master/py/desispec/scripts/specex.py#L214-L220

So we could modify the MPI redrock task to do the same thing.  In other words, every process does a try / except around their work and if an exception is raised some failed counter is incremented.  Then this counter is allreduced and every process raises an exception if some process raised.

**Comment by sbailey** [comment]
Documenting an in-person conversation:

"process raises an exception if some process raised" doesn't work for the case of redrock because there are internal MPI barriers.  If rank i throws an exception prior to the barrier, it jumps to the exception handling while the other ranks get stuck at the barrier waiting for rank i to join them, and thus they never finish to be able to allreduce, count exceptions, etc. and cleanly have everyone raise an exception.

We agreed to pursue my second option with a new `no_mpi_abort` flag that the pipeline could use to prevent rrdesi from calling MPI Abort.  In that case if one rank raises and exception, the other ranks get stuck at the barrier until the pipeline triggers the TimeoutError signal handler, and then they all end up raising an exception (but not killing off the entire MPI job).

And FWIW, the barrier logic in redrock is pretty fundamental to the data flow and wouldn't be trivial to remove without impacting efficiency.
