### ISSUE TITLE
boss.read_spectra() should promote input filename to list 

### ISSUE THREAD

**Issue by weaverba137** [desihub/redrock#172]
`redrock.external.boss.read_spectra()` takes a `list()` as input not a string.  Internally, it iterates over the items in the input filenames, but this operation is also valid on a string.   So for, example, it might try to open the file `'/'` when the input is `'/foo/bar.fits'`. This function should be able to detect that.

**Comment by sbailey** [comment]
I agree with this, but don't have the time to implement and test it myself right now.  @weaverba137 could you make this change?  Please also check if `redrock.external.desi` may have a similar problem with its readers.  Thanks.

**Comment by weaverba137** [comment]
Actually, `redrock.external.desi` already has the solution: when it receives a string instead of a list, it interprets that string as a shell glob, and uses `glob.glob()` to promote it to a list.  Is that the desired behavior for boss?
