### ISSUE TITLE
Fitting Failure Mode: Star fitted as Galaxy at Red shift 1.6

### ISSUE THREAD

**Issue by biprateep** [desihub/redrock#174]
These are examples from the mini-SV tile 63075 coadded files from 20200219. The spectra look like stars (K stars probably). The templates for galaxies at a redshift of ~1.6 seem to fit the overall spectral shape well (but not the absorption lines). Below are four examples of the same but plenty of such examples can be found in the above mentioned dataset
![Screenshot from 2020-02-26 02-53-28](https://user-images.githubusercontent.com/24821499/75325477-e750ab00-5846-11ea-91c7-8f4675f1cdc1.png)
![Screenshot from 2020-02-26 02-54-01](https://user-images.githubusercontent.com/24821499/75325478-e7e94180-5846-11ea-82ad-9425187a1b5b.png)
![Screenshot from 2020-02-26 02-56-01](https://user-images.githubusercontent.com/24821499/75325479-e7e94180-5846-11ea-9aaa-392c97030c1e.png)
![Screenshot from 2020-02-26 02-57-29](https://user-images.githubusercontent.com/24821499/75325480-e881d800-5846-11ea-9cc3-0b2ce219e007.png)

**Comment by moustakas** [comment]
Failures like these are being assessed more holistically as part of the work in #279.
