### ISSUE TITLE
Fitting Failure Mode: Stars fitted as LRGs at Red shift 0.5

### ISSUE THREAD

**Issue by biprateep** [desihub/redrock#175]
These are examples from the mini-SV tile 63075 coadded files from 20200219. The spectra look like stars (K stars probably). The templates for galaxies (LRGs) at a redshift of ~0.5 seem to fit the overall spectral shape well one. One of the absorption lines coincidentally match up but the observed spectra lacks the 4000 Angstrom break. Below are four examples of the same but plenty of such examples can be found in the above mentioned dataset.
![Screenshot from 2020-02-26 03-26-32](https://user-images.githubusercontent.com/24821499/75327499-81662280-584a-11ea-9bb7-8745ef6cc9de.png)
![Screenshot from 2020-02-26 03-27-10](https://user-images.githubusercontent.com/24821499/75327501-81feb900-584a-11ea-8c1e-232343e30a50.png)
![Screenshot from 2020-02-26 03-27-49](https://user-images.githubusercontent.com/24821499/75327504-82974f80-584a-11ea-9378-1ed6e7832398.png)
![Screenshot from 2020-02-26 03-28-22](https://user-images.githubusercontent.com/24821499/75327505-82974f80-584a-11ea-8034-0b4b271248ef.png)

**Comment by moustakas** [comment]
Failures like these are being assessed more holistically as part of the work in #279.
