### ISSUE TITLE
add better code and template version propagation

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#176]
* Add VERSION keywords to all redrock template files; currently only rrtemplate-galaxy.fits has that.  As a result, the propagated version strings in the redrock output are mostly "unknown".
* Add a version number to redrock-templates as a whole so that a single version number can describe a suite of templates.
* Propagate code versions from input files (check whether rrdesi isn't propagating them, or whether the coadds used for minisv2 didn't propagate version headers)
* Update rrdesi output to use `desiutil.depend` to add the redrock version, instead of RRVER.

Use case: visual inspections and bug reports should cite which version of redrock + templates was used, but we don't exactly make that easy for them right now to know from the output files...

**Comment by sbailey** [comment]
I added VERSION header keywords to the redrock-templates files, and a version.json file that can be used to track the versioning of the repo as a whole, i.e. which versions of which templates became a given redrock-templates tag).

For the purposes of data release 20.4 I'm going to call this "done" so it isn't a blocking factor, though additional changes should still be done on the rrdesi side to propagate these versions in a manner more consistent with the rest of desicode.  See last two bullets of original issue post.

**Comment by moustakas** [comment]
This will be done once #295 has been merged.
