### ISSUE TITLE
Triple-peak [OII] emission line profile

### ISSUE THREAD

**Issue by astro-blue** [desihub/redrock#179]
I found that occasionally there are broad [OII] emission lines with three peaks instead of two, which are captured by the model as well.

I am not sure whether this feature is built intentionally in the model or not. 

Here are a few examples in tile 67230 (20200315)
35185760097276520
35185760105664964
35185760101468277
35185766116101295
35185766116099530
35185766111905627
35185766111905239

In fact, the observed three-peak profile is likely real and could be due to AGN or merger
e.g., https://arxiv.org/abs/1208.2485

**Comment by moustakas** [comment]
@astro-blue, I'd like to close this ticket because I don't think there are any specific action items for Redrock itself. In addition, I don't have any recent reductions of tile 67230 I can look at (see #177 for additional context and details).

Great stuff, though!
