### ISSUE TITLE
improve rrdesi_mpi startup overhead

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#217]
On Perlmutter CPU nodes with `srun -n 128 -c 2 rrdesi_mpi ...`, it takes ~1 minute for it to wake up and do all the imports (all code on /global/common/software), and then the actual processing of 500 targets on a single petal takes <40 seconds.  i.e. there is a significant opportunity for overhead optimization.  Two routes to explore:

* docker/shifter containers should significantly reduce the import overhead, but by how much?
* accept the startup overhead, but add a desispec pipeline wrapper that only has to wake up once and then loops over petals calling `redrock.external.desi.rrdesi(comm)` multiple times for an expected runtime of ~60+10*40=460 seconds instead of ~10*(60+40)=1000 seconds.
* Or both.  On both CPU and GPU perlmutter nodes, redrock runs fast enough that it is wasteful to allocate 10 nodes to run 10 petals in parallel, vs. allocating 1 node and running 10 serially.

**Comment by sbailey** [comment]
A plot from @dmargala studying the import time in comparison to other steps vs. number of cores on Perlmutter CPU; there is lots of good information in here beyond just the import scaling:

![image-13](https://user-images.githubusercontent.com/218471/182729084-c4966b03-4515-48dd-8cbd-6cf7c1fd9487.png)

**Comment by marcelo-alvarez** [comment]
This is being addressed in [desispec/desi_zproc](https://github.com/desihub/desispec/tree/desi_zproc).

**Comment by sbailey** [comment]
A desispec pipeline wrapper, `desi_zproc`, was added in desihub/desispec#1904 .  This runs all 10 petals on a single node with a single MPI startup (not only for redrock, but also for spectral grouping, coadding, zmtl, afterburners, and qa).  Closing this ticket.
