### ISSUE TITLE
redrock GPU mode fails when ntargets < MPI size

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#221]
`rrdesi_mpi --gpu ...` fails when the number of targets being processed is smaller than the number of MPI ranks being used.  This can occur for healpix-based redshifts when a given healpix barely overlaps a tile resulting in a very small number of targets in that coadd.

To reproduce, create a test 10-target file:
```
from desispec.io import read_spectra, write_spectra
coadd = read_spectra('/global/cfs/cdirs/desi/spectro/redux/himalayas/tiles/cumulative/2312/20211102/coadd-0-2312-thru20211102.fits')
write_spectra('coadd-10.fits', coadd[0:10])
```

Then run redrock on that file:
```
srun -n 64 -c 2 --gpu-bind=map_gpu:3,2,1,0 --cpu-bind=cores \
    rrdesi_mpi -i coadd-10.fits -o redrock-10.fits --gpu --max-gpuprocs 4
```

that succeed with `-n 10` or less, but fails with `-n 11` or larger with:
```
--- Process 0 raised an exception ---
Proc 0: Traceback (most recent call last):
Proc 0:   File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/external/desi.py", line 787, in rrdesi
    scandata, zfit = zfind(targets, dtemplates, mpprocs,
Proc 0:   File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/zfind.py", line 222, in zfind
    local_targets, results = _rebalance_after_scan(targets, results)
Proc 0:   File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/zfind.py", line 122, in _rebalance_after_scan
    dist_targets = [flattened_targets[i[0]:i[0] + len(i)] for i in ix]
Proc 0:   File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/zfind.py", line 122, in <listcomp>
    dist_targets = [flattened_targets[i[0]:i[0] + len(i)] for i in ix]
Proc 0: IndexError: index 0 is out of bounds for axis 0 with size 0

MPICH Notice [Rank 0] [job id 3783842.0] [Mon Nov 28 15:34:46 2022] [nid001372] - Abort(0) (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0
```
The crash is unique to the GPU code path, which handles `dist_targets` somewhat differently than the CPU-only mode.

@dmargala (and @craigwarner-ufastro) please take a look.  I think/hope the fix is easy, but might involve some delicate indexing to avoid introducing a different bug.

This is a blocking bug for Himalayas and Iron healpix redshifts on GPUs, though we could fall back to doing healpix redshifts on CPUs if needed.

**Comment by craigwarner-ufastro** [comment]
Hi Steven,
Here is a quick and dirty fix that I believe works -- if you want me to 
submit a PR for this, I can do that a bit later tonight, separating it 
from my other outstanding PR items, but wanted to go ahead and reply 
with the fix.


@@ -99,7 +118,13 @@ def _rebalance_after_scan(targets, results):
          flattened_targets = [t for sl in lopsided_targets for t in sl]
          # Split targets into approximately equal lengths sublists
          ix = np.array_split(np.arange(len(flattened_targets)), 
len(lopsided_targets))
-        dist_targets = [flattened_targets[i[0]:i[0] + len(i)] for i in ix]
+        dist_targets = []
+        for i in ix:
+            if len(i) == 0:
+                dist_targets.append([])
+            else:
+                dist_targets.append(flattened_targets[i[0]:i[0] + len(i)])
+        #dist_targets = [flattened_targets[i[0]:i[0] + len(i)] for i in ix]

Craig

**Comment by sbailey** [comment]
@craigwarner-ufastro thanks, yes please submit a PR with this fix (not mixed in with other updates).  Your code suggestion is what I had in my head, but hadn't gotten to the point of implementing and testing whether it would trip over the empty lists in `dist_targets` etc.

**Comment by craigwarner-ufastro** [comment]
@sbailey should the PR be to the main or GPU branch?
