### ISSUE TITLE
Are penalties actually applied at the final sorting?

### ISSUE THREAD

**Issue by Waelthus** [desihub/redrock#248]
I looked at the zscan and fitz routines again and found a potential bug regarding final sorting:

- in the initial coarse redshift fitting, penalties for forbidden lines are applied (in the zscan.calc_zchi2 function: https://github.com/desihub/redrock/blob/2483c484cbccd6c785126c2d045e02deccf1ffe7/py/redrock/zscan.py#L746
- afterwards fits are performed within the fitz.fitz function which first gets the penalized chi2 values, searches for minima and then refits on a finer wavelength grid 
- this refit is done using zscan.calc_zchi2_batch https://github.com/desihub/redrock/blob/2483c484cbccd6c785126c2d045e02deccf1ffe7/py/redrock/fitz.py#L210 which does not report a penalty and does not use calc_zchi2 internally, so won't compute a penalty https://github.com/desihub/redrock/blob/2483c484cbccd6c785126c2d045e02deccf1ffe7/py/redrock/zscan.py#L657
- those chi2 values are then fit with a parabola https://github.com/desihub/redrock/blob/2483c484cbccd6c785126c2d045e02deccf1ffe7/py/redrock/fitz.py#L217 and the outputs of that fit are then used for the final sorting https://github.com/desihub/redrock/blob/2483c484cbccd6c785126c2d045e02deccf1ffe7/py/redrock/fitz.py#L289

So it looks like we're currently only applying the penalties on coarse fits and both the final reported chi2 and the final sort order are not including a penalty term.
How much this actually affects final redshifts remains to be seen.

**Comment by moustakas** [comment]
Possibly addressed in https://github.com/desihub/redrock/pull/296.

**Comment by sbailey** [comment]
Fixed by PR #296.  Closing.
