### ISSUE TITLE
Mismatch between DESI and SDSS galaxy redshifts

### ISSUE THREAD

**Issue by pbiswas82** [desihub/redrock#254]
We have noted mismatches in the redshifts given in the zall-pix-edr-vac.fits catalogue (DESI catalogue) when compared to the SDSS spectroscopic catalogue. We cross-matched the GALEX-SDSS-WISE LEGACY CATALOG (GSWLC) with sources in zall-pix-edr-vac.fits and noticed that some of the redshifts given in the DESI catalogue are drastically different than that in the GSWLC (which uses SDSS redshifts). In the following figure, we can see this.
![envden1](https://github.com/desihub/redrock/assets/145756313/fbfaaf8d-96b3-43a6-b506-ab8621a6ab26)
Following I have listed the DESI target ID, DESI redshift and redshift from the GSWLC for the four galaxies marked in the above figure:
1.
Target ID: 39633240163617085
DESI - z: 1.6529383334623118
GSWLC - z: 0.1165
Link to the spectra: https://www.legacysurvey.org/viewer/desi-spectrum/edr/targetid39633240163617085
2.
Target ID: 39633304151917538
DESI - z: 1.671210092601552
GSWLC - z: 0.0711
Link to the spectra: https://www.legacysurvey.org/viewer/desi-spectrum/edr/targetid39633304151917538
3.
Target ID: 39633345683918575
DESI - z: 1.2412686596561762
GSWLC - z: 0.0418
Link to the spectra: https://www.legacysurvey.org/viewer/desi-spectrum/edr/targetid39633345683918575
4.
Target ID: 39633339031750728
DESI - z: 1.657199768022857
GSWLC - z: 0.0107
Link to the spectra: https://www.legacysurvey.org/viewer/desi-spectrum/edr/targetid39633339031750728

If we go to the spectra links given above, we can examine the DESI spectrum. And if we put the redshift given by GSWLC, we will see that spectral lines are fitting correctly. Also, if we see these four objects in the Legacy Sky viewer (given on the right side in the spectra linked above), we will be able to understand from size and brightness that they are nearby galaxies, not galaxies at z> 1.

**Comment by moustakas** [comment]
Thank you for this report @pbiswas82. I have moved your issue to the relatively new "Redrock evaluator" repo (and am closing this ticket)--
https://github.com/desihub/rrevaluator/issues/3.

There, we will be tracking the performance of Redrock not just relative to SDSS, but other external and internal datasets and hope to have an update on your specific ticket soon based on a new set of galaxy templates.

**Comment by pbiswas82** [comment]
Dear all,
Thank you for the response. Looking forward to the update.

Regards,
Pralay Biswas
