### ISSUE TITLE
Inoue IGM transmission does not accept scalar redshifts, even though it claims to

### ISSUE THREAD

**Issue by dylanagreen** [desihub/redrock#257]
On the branch `fastpsec-pca-templates`, the full IGM transmission curve using the model from Inoue+ 14 is implemented for future use in redrock. A later GPU-ified version iterated upon this and now exists as the most up to date version. This function is (on line 714 of redrock.utils) `transmission_IGM` with the old version in `transmission_IGM_old`. The docstring for `transmission_IGM` (and `transmission_IGM_old`) claims:
> 3-> For legacy, it is still supported to pass zObj as a float and
    in this case, the return value will be a 1-d numpy array (nlambda).

This, however, does not seem to be true. The following minimal reproducible example fails:

```python
from redrock.utils import transmission_IGM
xmin = 2500
xmax = 6500
x = np.linspace(xmin, xmax, num=50)
z = 3.5
transmission_IGM(z, x)

----------------------------
    769 i = min_wave < 1220.
--> 770 T[i, :] = IGM.full_IGM(asarray(zObj[i]), lObs[i,:], use_gpu=use_gpu)
    771 if np.isscalar(zObj) and use_gpu:
    772     T = asarray(T)

> TypeError: 'int' object is not subscriptable
```

Note that I believe there are in fact two bugs here, the second hidden by the first. The first is outlined in the error message above, where `zObj[i]` is attempting to index a scalar, and the check for scalar `zObj` is only after running the full IGM. There is a second bug, namely, even if `zObj` is passed correctly to `full_IGM` there is an entirely separate instance inside the object class that also implicitly indexes on the input redshift, even if it is a scalar:

```python
from redrock.utils import Inoue14
xmin = 2500
xmax = 6500
x = np.linspace(xmin, xmax, num=50)
z = 3.5
igm = Inoue14()
igm.full_IGM(z, x)

----------------------------
    371 else:
    372     arrexp = np.exp
--> 374 tau_LS = self.tLSLAF(z, lobs, use_gpu=use_gpu) + self.tLSDLA(z, lobs, use_gpu=use_gpu)
    375 tau_LC = self.tLCLAF(z, lobs, use_gpu=use_gpu) + self.tLCDLA(z, lobs, use_gpu=use_gpu)
    377 ### Upturn at short wavelengths, low-z
    378 #k = 1./100
    379 #l0 = 600-6/k
    380 #clip = lobs/(1+z) < 600.
    381 #tau_clip = 100*(1-1./(1+np.exp(-k*(lobs/(1+z)-l0))))
----------------------------
    211 z2LAF = 4.7
    213 tLSLAF_value = np.zeros_like(lobs*l2).T
--> 215 x0 = (lobs / (1+zS)[:,None]) < l2
    216 x1 = x0 & (lobs < l2*(1+z1LAF))
    217 x2 = x0 & ((lobs >= l2*(1+z1LAF)) & (lobs < l2*(1+z2LAF)))

TypeError: 'int' object is not subscriptable

```

This problem is also evident in the `_old` version of the transmission_IGM:

```python
from redrock.utils import transmission_IGM_old
xmin = 2500
xmax = 6500
x = np.linspace(xmin, xmax, num=50)
z = 3.5
transmission_IGM_old(z, x)

----------------------------
    661 else:
    662     T = np.ones_like(lRF)
--> 663 for iz, myz in enumerate(zObj):
    664     if myz < 2.:
    665         continue

TypeError: 'int' object is not iterable
```

However, the second bug is not present in the old version of the object class function:
```python
from redrock.utils import Inoue14
xmin = 2500
xmax = 6500
x = np.linspace(xmin, xmax, num=50)
z = 3.5
igm = Inoue14()
igm.full_IGM_old(z, x)

---------------------------
array([...])
```

**Comment by sbailey** [comment]
Fixed in #271 for the transmission_Lyman wrapper, which accepts Inoue14 as one of the options, so I think this is fixed for practical purposes even if the the Inoue model itself requires vector inputs when used standalone.  Updating the example in the original post for what now works:
```python
from redrock.igm import transmission_Lyman
xmin = 2500
xmax = 6500
x = np.linspace(xmin, xmax, num=50)
z = 3.5
transmission_Lyman(z, x, model='Inoue14')  # outputs a 1D array, as expected
```
