### ISSUE TITLE
default SPECTYPE and SUBTYPE for ZWARN=NODATA targets

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#262]
Currently Redrock assigns an arbitrary SPECTYPE and SUBTYPE to spectra that are completely masked (ZWARN with NODATA bit set).  It might be less confusing to invent a different SPECTYPE/SUBTYPE/COEFF for the special case of completely meaningless or failed fits.

**Comment by djschlegel** [comment]
I went back to see what we did in SDSS.  I don't think we special-cased this, but the 0.5% of the spectra with no data were assigned CLASS="GALAXY",Z=0.  That seems to have confused people less.  If one were to invent a new SPECTYPE like "NONE", there should be a template of zeros associated with it.

**Comment by sbailey** [comment]
Related, arguably duplicate: #224

**Comment by sbailey** [comment]
A few issues to consider if we add a special SPECTYPE=NONE template case: when scanning templates over redshifts, we'd probably want to skip this case even if that template existed, but when loading spectra and rendering the models (e.g. with prospect) we'd probably want it to exist.  It's unclear which is the best default for load_templates.  For now we'll use the SDSS-style defaults of SPECTYPE=GALAXY Z=0 (see ticket #224) and I'm going to leave this ticket open but remove from Jura.

**Comment by sbailey** [comment]
PR https://github.com/desihub/redrock/pull/294 sets these cases to SPECTYPE='GALAXY' SUBTYPE='' COEFF=[0., 0., ...].

Reopen this PR for further discussion about a custom template if we find ourselves tripping over this case.
