### ISSUE TITLE
Add support for different templates using different IGM models

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#269]
For future templates, we seem to have converged on Inoue14 as the best IGM model.  However, we would still like to be able to evaluate old templates with the latest Redrock code, even if those templates were trained with a different IGM model.

Proposal: add new header keyword RRIGM that defines which IGM model to use: Inoue14, Calura12, Kamble20, and then propagate that choice to `transmission_Lyman` which would select the model to use.  Include support for past templates which don't have the RRIGM keyword, using their version number to know which model to use.

I'm working on this, but am filing this ticket for tracking.

**Comment by moustakas** [comment]
Probably done in #271 @sbailey?

**Comment by sbailey** [comment]
Yes, thanks for noticing this dangling ticket.  For the record, this was implemented in PR #271, where templates now have a header keyword **RRIGM** to specify which IGM model to use.  Supported values are **Calura12**, **Kamble20**, and **Inoue14**.  I put in support for legacy templates to derive which model to use based upon their version number, but IIRC this is now a required keyword for new templates.
