### ISSUE TITLE
consider adding a ZWARN bit which identifies significant inter-camera offsets

### ISSUE THREAD

**Issue by moustakas** [desihub/redrock#286]
I think we should consider adding a new ZWARN bit which flags statistically significant intercamera offsets which are often mistaken by Redrock as spectral breaks. 

E.g., here's one example which gets mistaken as a high-redshift QSO:

<img width="750" alt="Screenshot 2024-03-07 at 10 52 00 AM" src="https://github.com/desihub/redrock/assets/1431820/9f31b703-3113-43f9-baf9-cfe8ce084f34">

One simple implementation would be to compute the robust statistics (e.g., the iteratively clipped median and robust sigma) of the edges of each camera, say 50-100 pixels, and then look for an >N-sigma difference in the medians.

I'm certain I haven't thought through all the possible pitfalls, but it may be worth at least discussing something like this.

**Comment by araichoor** [comment]
for what is worth: wouldn t such cases be easily identified in the sky spectra?
like recording the median value (or something fancier) of the sky fibers for each petal and each amplifier (ie splitting the wavelength range in two and the fibers in two sets of 250 each); and turn on some warning if there are significant discrepancies?

**Comment by moustakas** [comment]
This discussion has moved to https://github.com/desihub/desispec/issues/2193 as a masking, pre-processing, and/or sky-subtraction issue.
