### ISSUE TITLE
add flexibility to the template io

### ISSUE THREAD

**Issue by ngbusca** [desihub/redrock#38]
The current template io has the template classes hardcoded. I'd like to suggest that the template info (such as spectype, redshift range, etc) be moved to the input .fits files. This would be useful if a user wants to add a template class (e.g. QSO_BAL), she would simply add a .fits file with the appropriate information. The io would loop over the existing target.fits files and read the necessary target information from them.

**Comment by sbailey** [comment]
Good idea.  Please implement that.  For backwards compatibility with the existing templates, I'd suggest that if a template does *not* have the keywords to specify the redshift range, spectype, etc., then the code should default to the parameters it uses now for the classes that it already knows about.  i.e. continue to work with the existing templates while also supporting the ability to add a new template file without having to change the code too.

**Comment by londumas** [comment]
@sbailey, Seems to me that this issue is fixed. What do you think?
