### ISSUE TITLE
Write rrboss wrapper script

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#4]
Write bin/rrboss wrapper script to read in idlspec2d spCFrame files and perform redshift fitting.  All BOSS-specific code should be isolated to this script and/or a redrock.survey.boss module.

**Comment by ngbusca** [comment]
I've implemented a first version of this in the branch rrboss. It runs now only on individual exposures, with a slightly different signature as rrdesi:

`
rrboss --indir platedir --allspec --zbest zbest.fits --output rrdetail.h5  --spall spAll.fits
`
spAll is necessary to get the thing_id (mapped to targetid) from the fiber information. 

I'll run a few tests.

**Comment by ngbusca** [comment]
@sbailey can I close this?

**Comment by sbailey** [comment]
Fixed by #37 (thanks!).
