### ISSUE TITLE
PlotSpec tries to read non existing target.coadd

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#45]
When using boss, we set `Targets` with `targets.append(Target(targetid, spectra, do_coadd=False))` the results is that `target.coadd` doesn't exist.
In  redrock/py/redrock/plotspec.py, the code tries to read non existing coadd `for spec in target.coadd:.

The solution is to replate this last line by:
```
        if hasattr(target,"coadd") and not target.coadd is None:
            specs_to_read = target.coadd
        else:
            specs_to_read = target.spectra
        for spec in specs_to_read:
```

**Comment by sbailey** [comment]
fixed by PR #46 (thanks @londumas)
