### ISSUE TITLE
CHI2 can be negative

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#48]
Among the 3,056,862 objects fit with rrboss 16,842 have CHI2<=0. Among them 18 have ZWARN=0.
They seem to be spectra with very few pixels.

Here is an example of a spectrum with only 13 valid pixels:
```
 target 3777552100761
znum spectype         z                zerr       zwarn       chi2     
---- -------- ----------------- ----------------- ----- ---------------
   0   GALAXY    0.684110380898 2.22265086481e-05     0 -0.679448604584
   1   GALAXY    0.963572171329 2.23922524482e-05     4   12.5200171471
   2   GALAXY    0.290527856756 1.25982246613e-05     0   18.2864579558
   3     STAR 0.000663565138503 1.45625809284e-05     4   84.2927164602
   4     STAR -0.00156789399554  8.7091695412e-06     4   91.2040898193
   5     STAR 0.000883054358289 1.30696754679e-05     4   97.3096341818
   8      QSO     3.49351411723 0.000142390448734     4   107.733959794
   9      QSO      1.5153153726  7.9556667662e-05     4   107.993852615
  10      QSO     1.23146576711 6.88101846302e-05     4   110.841642439
```

![capture d ecran de 2017-11-27 15-49-00](https://user-images.githubusercontent.com/3166436/33293571-7fe72662-d38a-11e7-917f-f6252172021e.png)

Here is the full list of these 18 objects:
```
plate, mjd, fiber, targetid
[[         3606         55182           547 3606551820547]
 [         3777         55210           761 3777552100761]
 [         3809         55533           646 3809555330646]
 [         4711         55737           817 4711557370817]
 [         4953         55749           136 4953557490136]
 [         5375         55973           400 5375559730400]
 [         6465         56279             6 6465562790006]
 [         7254         56625           511 7254566250511]
 [         7261         56603           714 7261566030714]
 [         7261         56603           970 7261566030970]
 [         7581         57195           426 7581571950426]
 [         7705         57332           782 7705573320782]
 [         8284         57419           761 8284574190761]
 [         8366         57432           507 8366574320507]
 [         8789         57358           500 8789573580500]
 [         4368         55559           507 4368555590507]
 [         4406         55858           501 4406558580501]
 [         4532         55559           761 4532555590761]]
```

**Comment by londumas** [comment]
It seems redrock doesn't store the number of pixels used to fit. Is it true @sbailey?

**Comment by sbailey** [comment]
chi2 = sum( (flux-model)**2 * ivar ) so the only way I see for chi2 to be negative would be for ivar to be negative, which should never happen (unless perhaps it is flagging some other error and should also be masked).  Could you @londumas check that for this target?

I think you are correct about not tracking the number of pixels used, which is problematic when there are masked pixels such that the number of pixels used varies with the redshift of the template.  I submitted issue #49 to track and fix this.

**Comment by londumas** [comment]
After a long time searching, I am starting to understand what is happening:
the chi2 is not define as `sum( (flux-model)**2 * ivar )`, but as the min of a fitted parabola around the minimum:
In py/redrock/fitz.py, we have `def minfit(x,y)`, sometimes the minimum `y0` is less than zero.
I have to understand when and why does this occure

**Comment by londumas** [comment]
Here are the x,y input of the `minfit` function:
```
[ 0.7584228   0.75859634  0.75876988]
[ 2.31879114  0.09150874  0.3100931 ]
```

Indeed the chi2 is negative.

![capture d ecran de 2017-11-28 12-31-06](https://user-images.githubusercontent.com/3166436/33340012-1379f4ce-d438-11e7-90b6-e0fe243ba7d1.png)

```
import scipy as sp

x = sp.array([ 0.7584228,0.75859634,0.75876988])
y = sp.array([ 2.31879114,0.09150874,0.3100931 ])

a,b,c = sp.polyfit(x,y,2)
print a, b, c

###
import matplotlib.pyplot as plt
x = sp.arange(0.758,0.759,0.00001)
y = a*x**2 + b*x + c
plt.plot(x,y,linewidth=4,label="fit",color="red")
x = sp.array([ 0.7584228,0.75859634,0.75876988])
y = sp.array([ 2.31879114,0.09150874,0.3100931 ])
plt.plot(x,y,linewidth=4,label='data',color="blue")
plt.xlabel("x")
plt.ylabel("y")
plt.legend(fontsize=20, numpoints=1,ncol=2, loc=1)
plt.grid()
plt.show()
```

**Comment by londumas** [comment]
@sbailey, how do you feel about adding a condition on `y0` in `minfit`?

**Comment by londumas** [comment]
fixed in fix_issue_48

**Comment by londumas** [comment]
fixed
