### ISSUE TITLE
track number of degrees of freedom used in chi2 calculations

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#49]
redrock incorrectly doesn't track the number of pixels used in the chi2 vs. redshift calculations, which causes a bias when there are masked pixels such that the number of degrees of freedom varies with the redshift of the template.

Related: redrock also doesn't track that different templates have different numbers of eigenvectors.  This can make a difference for borderline cases of selecting between two almost-equally-good fits from different templates.

**Comment by londumas** [comment]
If we track this number, we could use it to compare different fits with the chi2 probability. What do you think?

**Comment by londumas** [comment]
@sbailey, do you want the number of pixels and of parameters to be stored in the zbest file ?

**Comment by sbailey** [comment]
A correction to the original post: masked pixels *don't* cause a change to the number of degrees of freedom vs. redshift, because the data mask is always the same regardless of the redshift of the template being tested.  i.e. this isn't as big a problem as I originally thought.

None-the-less, it would still be handy to add 2 additional columns with the number of unmasked pixels used and the number of eigenvectors of the best fit template.

@julienguy and I just had a long conversation that filled a whiteboard with matrix algebra that might solve this in a more rigorous way, but in the meantime having that extra information could be useful.

**Comment by londumas** [comment]
The templates have different number of eigenvectors. So setting the best fit as the one with the lowest chi2 is not perfect. Also comparing znum_i to znum_i+1 to a Delta chi2 of 9, is not correct.
template nb_vectors
-------------------------
Star-A, 5
Star-B, 5
Star-F, 5
Star-G, 5
Star-K, 5
Star-M, 5
Galaxy, 10
QSO, 4

**Comment by londumas** [comment]
fixed.
