### ISSUE TITLE
rrboss lambda_min decision

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#52]
https://github.com/desihub/redrock/blob/22e4a18a1d738a40ad6f6929532d14f99742d798/py/redrock/external/boss.py#L104

In rrboss (py/redrock/external/boss.py), we set lambda_min as 3500, this captures the imperfect correction of the CCD efficiency. Smee et al encourages to use 3611A
>In between these detected arc lines for SDSS (3902 ̊A –9149 A) and BOSS (3611 A – 10140A), the wavelength solutions are typically accurate to 3 km/s.  Beyond those wavelengths the solutions are extrapolated and the accuracy has not been evaluated.

Here is an example of a spectrum (7895573720001), you can see that the error is small but the flux is very big at low lambda_obs
![flux_7895573720001](https://user-images.githubusercontent.com/3166436/33491670-32bee690-d678-11e7-813d-41e62f96c5d2.png)
![error_7895573720001](https://user-images.githubusercontent.com/3166436/33491684-39c03e4e-d678-11e7-960e-2ad85d3af942.png)

**Comment by ngbusca** [comment]
@londumas are those pixels unmasked?

**Comment by londumas** [comment]
@ngbusca, I don't understand, what do you mean ?
All the pixels in this spectrum have ivar>0. and and_mask==0

**Comment by ngbusca** [comment]
@londumas I was asking whether you were plotting flux*(ivar>0)*(mask==0) or just flux...

**Comment by londumas** [comment]
@ngbusca, I plot flux[ (ivar>0) & (end_mask==0) ].
I don't look at the or_mask, or at other data. maybe some other info flags these outlier.

**Comment by ngbusca** [comment]
This is very weird. If I look at the individual exposures (there's only one for this object), there are no outliers:

![image](https://user-images.githubusercontent.com/4727509/33494814-d88a0e78-d6c4-11e7-8208-2c514199bae0.png)

**Comment by londumas** [comment]
Interesting... @ngbusca, do you confirm that the spplates has one ?

**Comment by ngbusca** [comment]
yep, here's the header from the spPlate:

  EXPID01 = 'b1-00210498-00210497-00210496' / ID string for exposure 1
  EXPID02 = 'b2-00210498-00210497-00210496' / ID string for exposure 2
  EXPID03 = 'r1-00210498-00210497-00210496' / ID string for exposure 3
  EXPID04 = 'r2-00210498-00210497-00210496' / ID string for exposure 4 
  NEXP_B1 =                    1 / b1 camera number of exposures 
  NEXP_B2 =                    1 / b2 camera number of exposures
  NEXP_R1 =                    1 / r1 camera number of exposures
  NEXP_R2 =                    1 / r2 camera number of exposures

**Comment by londumas** [comment]
It seems to be a eBOSS pipeline issue since it is present in v5_10_0 (blue) but not in v5_10_7 (green).
![flux_7895573720001_compare_v5_10_0__v5_10_7__zoom](https://user-images.githubusercontent.com/3166436/33509830-4914b632-d6c2-11e7-8ab8-3e8e24a099ae.png)

**Comment by londumas** [comment]
Not a redrock bug, but a boss-pipeline bug
