### ISSUE TITLE
Add white dwarf templates

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#55]
In the desi meeting, there was a request for adding white dwarf templates.

**Comment by londumas** [comment]
I found this paper from SDSS-III, Kepler et al 2015. (https://arxiv.org/pdf/1510.08409.pdf)
I haven't found any PCA of white dwarf on ADS.
@sbailey, do you know of any?
Or should I create one from their catalog and your sbailey/empca code?

**Comment by moustakas** [comment]
We already have a white dwarf template set, for both DA and DB subtypes. It should be straightforward for @sbailey to include these in redrock.

**Comment by sbailey** [comment]
`redrock/bin/rrstartemplate` has the code for how the other types were generated, and could serve as a basis for how to make the redrock WD templates, with the substitution of STAR -> WD and not making the TEFF cuts for the subtypes.  Wouldn't take me long if I could find the time, but @londumas or others are also welcome to contribute WD templates in redrock format.

**Comment by londumas** [comment]
I have created a spectype=STAR, subtype=WD-DA template using desisim.templates.WD.
On a sample of plates, the results are:
    - 0.12% of previously called galaxies, become stars.
    - a large portion of A, B and F stars become WD-DA
    - visual inspection confirms that the previously called galaxies were in fact stars.
    - but not always WD-DA according to the pipeline

master vs. branch (in %)

GALAXY GALAXY 99.8791723305
GALAXY STAR 0.120827669536

A A 60.6765327696
A WD-DA 39.3234672304

B B 19.465648855
B WD-DA 80.534351145

F F 93.6108422072
F WD-DA 6.38915779284

G G 99.9185336049
G WD-DA 0.081466395112

K K 100.0

M M 100.0

**Comment by sbailey** [comment]
fixed by #101 and desihub/redrock-templates#2
