### ISSUE TITLE
add priors

### ISSUE THREAD

**Issue by ngbusca** [desihub/redrock#60]
Is there a way to add a gaussian prior to the redshift fit or interest in implementing that? I volunteer to do it if the answer is "no, yes"

**Comment by londumas** [comment]
@ngbusca, what is the "redshift fit" ?

**Comment by ngbusca** [comment]
@londumas I mean adding a term to the chi2 of the form (z - z_ext)^2/sigma_ext^2 where z_ext and sigma_ext are externally provided to the code. 

I guess it could be added as a module that reprocesses the rrdetails, this way I wouldn't need to change anything within zscan. It doesn't need to be part of redrock, but it's practical to have it there.

**Comment by londumas** [comment]
@ngbusca, sorry I was confused with another repository. I didn't see it was redrock.
I don't see when it could be useful to have a Gaussian prior. When would you see it useful?

**Comment by ngbusca** [comment]
@londumas it could be useful if you have an external measurement of the redshift that is not very precise (like a visual scan or similar) and you want to improve it with redrock.

**Comment by sbailey** [comment]
I think I'd prefer a solution that re-loads the chi2 vs. z from the hdf5 file, updates the chi2 with whatever prior is wanted, and then call fitz again to get the new set of minima.  Doing that may be messier than it needs to be, so it would be useful to write a brief tutorial-style demo of how that is done and then consider if there is something that would make it easier.

For consideration: do you really want a gaussian prior (that necessarily biases the answer toward the middle of that), or perhaps instead a flat redshift window with a penalty outside the window?

**Comment by ngbusca** [comment]
@sbailey Thanks for the input. I'll write some proposal code and we can improve from there. I'll leave the option of the type of prior open to the user to choose (with explicit options for gaussian and boxcar and such that it's easy to add other functional forms).

**Comment by moustakas** [comment]
Apologies for hijacking this thread -- as this should really be a separate issue -- but another valuable development for redrock would be to include the object photometry when constructing P(z).  This should help both with increasing delta-chi2 between redshifts of a a given spectral template type and with classification (i.e., P(z) across different spectral types).

**Comment by sbailey** [comment]
implemented in #152 (thanks @londumas)
