### ISSUE TITLE
redrock performance on Superset_DRQ and dc17b

### ISSUE THREAD

**Issue by ngbusca** [desihub/redrock#64]
I've shown these results elsewhere, but I'm summarizing them here as a useful benchmark for development and as a possible guideline for prioritizing improvements.

Below I compare the performance of redrock on BOSS data using the sample of quasar targets, that was (almost) fully visually inspected. I'm using the redrock run available [at Utah](https://data.sdss.org/sas/ebosswork/eboss/sandbox/desiwork/rrboss/spplates/redrock_zbest_dr14.fits) compared to the [superset_drq](https://data.sdss.org/sas/dr12/boss/qso/DR12Q/Superset_DR12Q.fits) "truth table" . The following table summarizes the results on classification:

                            Super_DRQ
                 STAR     GALAXY    QSO_LZ    QSO_HZ     BAD
                0.553      0.004    <0.001   < 0.001     0.021    STAR
    rrboss      0.058      0.969     0.124    0.036      0.537    GALAXY
                0.002      0.002     0.828    0.007      0.068    QSO_LZ
                <0.001     <0.001    0.009    0.935      0.018    QSO_HZ
                0.386      0.025     0.039    0.022      0.356    ZWARN != 0
                205101     22776    106760    190181     19255    # of objects

Columns correspond to the Super_DRQ classification while the rows to the rrboss classification (with ZWARN==0), or ZWARN != 0 (second to last row). Entries indicate the fraction of spectra out of the total number of spectra in the corresponding super_drq class. 

The following plot compares the redshift of objects classified as quasars by rrboss to the redshift in Superset_DRQ. The points mostly cluster along the diagonal, but there's still quite a significant line confusion. 

![image](https://user-images.githubusercontent.com/4727509/34762011-d08c96a2-f5ee-11e7-8813-78003b9a5f4f.png)

**Comment by ngbusca** [comment]
Here's the same thin but using all QSO targets from dc17b:

                    TRUTH
             STAR     GALAXY    QSO_LZ    QSO_HZ    
             0.024    <0.001    <0.001    <0.001    STAR
    rrdesi   0.036     0.978     0.111    <0.001    GALAXY
            <0.001    <0.001     0.862    <0.001    QSO_LZ
            <0.001    <0.001     0.001     0.989    QSO_HZ
             0.940     0.021     0.027     0.011    ZWARN!=0

This table shows that most stars selected as QSO targets get a ZWARN!=0. For other objects,  the classification performance seems optimistic in simulations (not surprisingly), specially for high-redshift quasars. 

The plot below shows the redshifting performance. Here, simulations are also quite optimistic compared to real data.

![image](https://user-images.githubusercontent.com/4727509/34799959-8a04aae0-f66a-11e7-8e6c-c70fb0277856.png)

**Comment by ngbusca** [comment]
Here's the performance using the latest zbest file from @londumas. There's quite a bit of improvement for the STAR class:

                        Super_DRQ
                 STAR     GALAXY    QSO_LZ    QSO_HZ     BAD
                0.751      0.005    <0.001   < 0.001     0.029    STAR
    rrboss      0.059      0.970     0.126    0.036      0.539    GALAXY
                0.002      0.002     0.831    0.007      0.071    QSO_LZ
               <0.001     <0.001     0.009    0.935      0.018    QSO_HZ
                0.187      0.023     0.034    0.021      0.343    ZWARN != 0
                205203     22783    106821    190322     19272    # of objects

**Comment by londumas** [comment]
@ngbusca,

> This table shows that most stars selected as QSO targets get a ZWARN!=0.
Are you using the latest redrock, i.e. the master?

**Comment by ngbusca** [comment]
I used the available zbest for dc17b that were run just before the december meeting.

**Comment by londumas** [comment]
@ngbusca, then this explains this result. Current version should be way better.
> This table shows that most stars selected as QSO targets get a ZWARN!=0.

**Comment by ngbusca** [comment]
@londumas are there plans to rerun redrock on dc17b?

**Comment by londumas** [comment]
This is more a question for @sbailey.

**Comment by sbailey** [comment]
Ted is converging on a MPI refactor of redrock.  When that is ready, I will rerun it on dc17b as a stress test (and if it passes, that will also be useful for this study).

**Comment by ngbusca** [comment]
Here's the same thing for idlspec1d:

                       Superset_DRQ
               STAR     GALAXY    QSO_LZ    QSO_HZ     BAD
              0.659      0.003     0.001    <0.001     0.029    STAR
    spAll     0.008      0.911     0.004    <0.001     0.539    GALAXY
              0.012      0.031     0.915    0.001      0.047    QSO_LZ
             <0.001      0.002     0.008    0.966      0.020    QSO_HZ
              0.321      0.052     0.072    0.033      0.573    ZWARN != 0
             206275      22795    106855    190377     21554    # of objects

Here's the redshift performance (only on ZWARN==0):

![image](https://user-images.githubusercontent.com/4727509/34812497-7d5f718c-f6ae-11e7-946d-b28b69fc190d.png)

**Comment by sbailey** [comment]
Thanks for these comparisons, @ngbusca et al.

For the Super_DRQ QSO_LZ that redrock identifies as GALAXY, could you quantify what fraction have the correct redshift anyway?  There was a telecon comment awhile back that many of these are AGNs with both galaxy-like and QSO-like features such that redrock was getting the redshift right anyway while calling it a GALAXY instead of a QSO.  I'm sure this isn't the full explanation for the poor QSO_LZ performance since dc17b didn't have AGN-like objects but also had a significant fraction of QSO_LZ -> GALAXY identifications.

**Comment by sbailey** [comment]
These are useful tables; followup actions have been posted as other tickets (#39, #56, #60, #68, #85).  Closing this one.
