### ISSUE TITLE
smart coadds to reject cosmics

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#68]
~90% of our DESI tiles will have multiple exposures, which gives the opportunity to identify cosmic rays while doing the internal coadd prior to redshift fitting.  A brute force median isn't so useful with only two exposures, but one could still look for large positive outliers that are inconsistent with the other exposure and inconsistent with interpolation from neighboring pixels.  e.g. it is pretty easy to identify by eye which pixel is the contaminated one here:
![blat](https://user-images.githubusercontent.com/218471/35071930-62d0ed4e-fb97-11e7-8158-02f54b1f25d4.png)
Be careful and test a lot since there will be many corner cases where we could reject the wrong thing (what if two pixels are contaminated?  What about pixels neighboring masked pixels?  How about pixels at the very peak of a real spectra feature where interpolation of the neighboring pixels isn't a good predictor? ...)

**Comment by sbailey** [comment]
Alas, this started in 18.3 and got punted to 18.6 then 18.9 and now 18.10...

Documenting idea from Julien: do the filter on testing the consistency of the derivatives of the spectra, not on the raw flux values.

**Comment by julienguy** [comment]
Implemented in PR #156
