### ISSUE TITLE
`n_target` should be `n_targets`

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#74]
https://github.com/desihub/redrock/blob/d0a32603c9d0c26c792eca18a17629db83c09ff4/py/redrock/external/boss.py#L314

In the new master, rrboss is broken: `n_target` should be `n_targets`.
Why even creating `n_targets`? We could simply use `args.ntargets`

```
    n_targets = None
    if args.ntargets is not None:
        n_targets = args.ntargets

    first_target = None
    if args.mintarget is not None:
        first_target = args.mintarget
    elif n_targets is not None:
        first_target = 0
```

```
        if args.ntargets is not None:
            targets = targets[first_target:first_target+n_targets]
            meta = meta[first_target:first_target+n_targets]
```

**Comment by sbailey** [comment]
Thanks for catching this (unfortunately I only tested rrdesi, not rrboss).  Please go ahead and fix (but make sure that all combinations work: only --mintarget, only --ntargets, or both --mintarget and --ntargets).

Related to #70 #71 and #73.
