### ISSUE TITLE
Systematic error in quasar redshift due to Lya forest

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#85]
The following plot shows 1000 quasars generated with `desisim.templates.QSO()` and fitted with redrock.
Blue points give results with Lya forests, orange points give results without Lya forests
The idea is to test to convolve the first eigenspectra of quasar templates with the PDF (lya+lyb+...) and see if the systematic error can be removed or reduced.

![systematic_error_redshift_qso](https://user-images.githubusercontent.com/3166436/35306115-772a7b54-0059-11e8-9cf8-69b81e0dae03.png)

**Comment by londumas** [comment]
Tested with a simple model, and seems to work well.
A more complete model should take the resolution of pixels into account, the presence of Ly-beta, Ly-gamma, ...

![systematic_error_redshift_qso_correction](https://user-images.githubusercontent.com/3166436/35308495-33bb7cfe-0065-11e8-8325-ab7a080d9722.png)


```
def mean_transmitted_flux_fraction(lRF,zpix):
     f = np.ones(lRF.size)
     w = lRF<1215.67
     f[w] = np.exp(-0.0023*(1.+zpix[w])**3.64)
     return f
```
Needs to modify redrock at two different places:

    - py/redrock/templates/DistTemplate
```
        for i, z in enumerate(myz):
            for k in list(self._dwave.keys()):
                lRF = self._dwave[k]/(1.+z)
                zpix = self._dwave[k]/1215.67-1.
                data[i][k][:,0] *= mean_transmitted_flux_fraction(lRF,zpix)
```
    - py/redrock/fitz/fitz()
```
            for k in list(dwave.keys()):
                lRF = dwave[k]/(1.+z)
                zpix = dwave[k]/1215.67-1.
                binned[k][:,0] *= mean_transmitted_flux_fraction(lRF,zpix)
```

**Comment by londumas** [comment]
Here are two plots giving:
    - blue: master ( no correction )
    - orange (correcting for the transmitted flux fraction)
    - green (correcting for the transmitted flux fraction + capping the data weight blue-ward of the forest)
The black vertical lines give the redshift when the CIV and Lya lines appear in the data (i.e. lObs>3600.)

![systematic_error_redshift_qso_correction_capweights](https://user-images.githubusercontent.com/3166436/35360068-b266ffba-0119-11e8-8a9e-93a7e77d7285.png)

![systematic_error_redshift_qso_correction_capweights__distribution](https://user-images.githubusercontent.com/3166436/35360067-b24edc28-0119-11e8-8b44-19a794e8cb6c.png)

**Comment by londumas** [comment]
Same result using `desisim.templates.SIMQSO()`

**Comment by londumas** [comment]
@sbailey, here is the current status on the issue:
The current fix works very well on desisim, but it fails on BOSS data.
The reason is that the current PCA base is not corrected for the Lyman-series absorption. See issue
https://github.com/desihub/desisim/issues/323.
The solution would be to produce a new quasar PCA base where the data would be corrected for the absorption in the Lyman-series and in the Lyman-limit.
What do you think?

**Comment by moustakas** [comment]
Why not just re-derive coefficients from a QSO template set generated using `simqso`?

**Comment by londumas** [comment]
@moustakas, why not. Could you link me to the doc or a paper explaining simqso? I need to know how the spectra are build and if they are unabsorbed or have the Lyman-series and the Lyman-limit.

**Comment by sbailey** [comment]
Progress has been made on this via #104, but more work is to be done on the template side, so leaving this open for now and moving from 18.3 to 18.6 project.

**Comment by londumas** [comment]
Similar issue as https://github.com/desihub/redrock/issues/106
